play.http.secret.key = "gO=fC5t;PbSBsp<HjI5?LAMD@PBqp7tn9W[er?nsV4>X0rug<u19W/u9b=x6?Aj6"

play.filters.hosts {
  allowed = [
    "pacificum.org", "www.pacificum.org"
    "localhost:9000",
  ]
}

play.filters.enabled += play.filters.https.RedirectHttpsFilter
play.filters.https.xForwardedProtoEnabled = true
